// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type EditPostion struct {
	ID          string `json:"id"`
	PostionName string `json:"postion_name"`
	Salary      string `json:"salary"`
}

type NewUser struct {
	Name        string  `json:"name"`
	Dob         string  `json:"dob"`
	Address     string  `json:"address"`
	PostionName *string `json:"postion_name,omitempty"`
	Salary      *string `json:"salary,omitempty"`
}

type Position struct {
	ID          string `json:"id"`
	UserID      string `json:"user_id"`
	PostionName string `json:"postionName"`
	Salary      string `json:"salary"`
}

type User struct {
	ID       string    `json:"id"`
	Name     string    `json:"name"`
	Dob      string    `json:"dob"`
	Address  string    `json:"address"`
	Position *Position `json:"position"`
}
